export const actionType = {
    LOAD_PRODUCTS : "LOAD_PRODUCTS",
    DETAILS_PRODUCT : "DETAILS_PRODUCT",
    REGISTER_USER: "REGISTER_USER",
    LOGIN_USER : "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    CATCH_ERROR: "CATCH_ERROR",
    GET_MESSAGE: "GET_MESSAGE",
    DISMISS_MESSAGE: "DISMISS_MESSAGE",
    LOADING_STATE: "LOADING_STATE"
}